name: CI
on: [push]
jobs:
  Eslint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i
      - name: Run Eslint
        run: npm run lint
